// Generated by typings
// Source: typings/custom/pluralize.d.ts
declare module "pluralize" {

  export default function  pluralize(word:string,count?: number, includeCount?: boolean);

  // default export = pluralize;
}
